name: Deploy C# Blob Trigger Function (Manual or Auto)

on:
  workflow_dispatch:
    inputs:
      function_app_name:
        description: "Azure Function App name"
        required: true
        default: "AIHACK-FUNCTIONAPP-GRP03-DOTNET"
      resource_group:
        description: "Resource group"
        required: true
        default: "AIHACK-RG-GRP03"
      publish_profile_secret:
        description: "Name of repo secret containing publish profile XML"
        required: true
        default: "AZURE_FUNCTIONAPP_PUBLISH_PROFILE"
  push:
    branches: [ main ]
    paths:
      - 'csharp-functions/**'
      - '.github/workflows/deploy-csharp-functions.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build & Deploy (.NET Blob Trigger)
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        working-directory: csharp-functions
        run: dotnet restore

      - name: Build
        working-directory: csharp-functions
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        working-directory: csharp-functions
        run: dotnet publish ProcessKTDocumentFunction.csproj -c Release

      - name: Diagnostics - List publish output
        working-directory: csharp-functions/bin/Release/net8.0/publish
        run: |
          echo "Listing publish directory contents:" 
          ls -R || dir
          echo "Check host.json:" 
          cat host.json || type host.json
          echo "Show functions metadata (new .NET 8 isolated consolidation):"
          if [ -f functions.metadata ]; then
            head -c 2000 functions.metadata || true
          else
            echo "functions.metadata not found (older SDK would emit function.json)"
          fi
          echo "Done diagnostics."

      - name: Validate build produced at least one function (functions.metadata aware)
        working-directory: csharp-functions/bin/Release/net8.0/publish
        run: |
          if [ -f functions.metadata ]; then
            if grep -q 'ProcessKTDocument' functions.metadata; then
              echo "Found ProcessKTDocument in functions.metadata"
              exit 0
            else
              echo "functions.metadata present but function name not found" >&2
              exit 1
            fi
          fi
          COUNT=$(find . -name function.json | wc -l || echo 0)
          echo "Legacy function.json count: $COUNT"
            if [ "$COUNT" -gt 0 ]; then
              echo "Legacy function.json files found (acceptable)"
              exit 0
            else
              echo "ERROR: Neither functions.metadata nor function.json present" >&2
              exit 1
            fi

      - name: Deploy via Publish Profile
        uses: azure/functions-action@v1
        with:
          app-name: ${{ github.event.inputs.function_app_name }}
          package: csharp-functions/bin/Release/net8.0/publish
          publish-profile: ${{ secrets[github.event.inputs.publish_profile_secret] }}

      - name: Echo deployed target
        run: echo "Deployment attempted to Function App: ${{ github.event.inputs.function_app_name }}"

      - name: Post-Deploy Reminder
        run: |
          echo "If not already set, configure OpenAI & Speech settings on the Function App." 
